---
- name: Playbook to install docker and tree using loop
  hosts: all
  become: true
  tasks:
  - name: Installing list of packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - docker
      - tree
...
